// GET_ALL_POKEMON //
export const GET_ALL_POKEMON_REQUEST = 'GET_ALL_POKEMON_REQUEST'
export const GET_ALL_POKEMON_SUCCESS = 'GET_ALL_POKEMON_SUCCESS'
export const GET_ALL_POKEMON_FAILED = 'GET_ALL_POKEMON_FAILED'

// GET_POKEMON_SPECIES //
export const GET_POKEMON_SPECIES_REQUEST = 'GET_POKEMON_SPECIES_REQUEST'
export const GET_POKEMON_SPECIES_SUCCESS = 'GET_POKEMON_SPECIES_SUCCESS'
export const GET_POKEMON_SPECIES_FAILED = 'GET_POKEMON_SPECIES_FAILED'

// GET_POKEMON_DETAIL //
export const GET_POKEMON_DETAIL_REQUEST = 'GET_POKEMON_DETAIL_REQUEST'
export const GET_POKEMON_DETAIL_SUCCESS = 'GET_POKEMON_DETAIL_SUCCESS'
export const GET_POKEMON_DETAIL_FAILED = 'GET_POKEMON_DETAIL_FAILED'